config/routes.rb
HomepageProvider::Application.routes.draw do

  resources :accounts do
    resource :homepage
  end
  match '/accounts/:id/homepage', to: 'homepages#show', via: 'get', as: 'show_account_homepage'

  match '/homepage/:id', to: 'homepages#show', via: 'get', as: 'show_homepage'
  match '/homepages/', to: 'homepages#index', via: 'get'
  match '/homepages/:id/', to: 'homepages#update', via: 'put', as: 'save_homepage'

  authenticated :user do
    root to: 'accounts#index', as: :authenticated_root
  end

  unauthenticated do
      root :to => 'welcome#index'
      match '/learn_more', to: 'welcome#learn', via: 'get'
  end

  devise_for :users

  get "welcome/help"
  

end

app/models/account.rb
class Account < ActiveRecord::Base
	after_create :build_default_homepage
	belongs_to :user, dependent: :destroy
	has_one :homepage

	private
		def build_default_homepage
		  homepage = create_homepage(content: "<h1>Hello, World!</h1><p>This is a fresh Homepage! If you are the owner, you can use <b>Spooner</b> below to edit it.<br>have fun!</p>")
		  self.homepage_id = homepage.id
		  save
		end
end


		def build_default_account
		  account = create_account(nickname: self.email)
		  self.account_id = account.id
		  save
		end

app/models/homepage.rb
class Homepage < ActiveRecord::Base
	belongs_to :account, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  	# Include default devise modules. Others available are:
  	# :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	after_create :build_default_account
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable
	has_one :account, dependent: :destroy

	private
		def build_default_account
		  account = create_account(nickname: self.email)
		  self.account_id = account.id
		  save
		end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_action :set_page_information

  respond_to :html

  def index
    @accounts = Account.all
    respond_with(@accounts)
  end

  def show
    respond_with(@account)
  end

  def new
    @account = Account.new
    respond_with(@account)
  end

  def editl
  end

  def create
    @account = Account.new(account_params)
    @account.save
    respond_with(@account)
  end

  def update
    @account.update(account_params)
    respond_with(@account)
  end

  def destroy
    @account.destroy
    respond_with(@account)
  end

  private
    def set_account
      @account = Account.find(params[:id])
    end

    def account_params
      params.require(:account).permit(:first_name, :last_name, :nickname, :paypal_address)
    end

    def set_page_information
      @page_title = 'Accounts'
      @page_icon = 'info'
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  before_action :set_account, only: [:show, :edit, :destroy]
  before_action :set_homepage, only: [:show, :edit, :update, :destroy]
  # before_action :set_header, only: [:show]
  before_action :set_page_information


  respond_to :html

  def index
    @homepages = Homepage.all
    respond_with(@homepages)
  end

  def show

    if user_is_visitor?
      @header = false
      @footer = true 
    end
  end

  def new
    @homepage = Homepage.new
    respond_with(@homepage)
  end

  def edit
  end

  def create
    @homepage = Homepage.new(homepage_params)
    @homepage.save
    respond_with(@homepage)
  end

  def update
    @homepage = Homepage.find(params[:id])
    @homepage.content = Homepage.find(params[:id])
    @homepage.account_id = 1
    @homepage.update(homepage_params)
    respond_with(@homepage)
    after_save { create_css_file }
  end

  def destroy
    @homepage.destroy
    respond_with(@homepage)
  end

  def user_is_visitor?
    return true if !user_signed_in? || @account.user != current_user
  end

  def save_css_file
    #
  end

  def create_css_file
    path = "/user_files/css/#{@account_id}.css"
    content = @account.content
    File.open(path, "w+") do |f|
      f.write(content)
    end
  end

  private
    def set_account
      @account = Account.find(params[:account_id])
    end

    def set_homepage
      @homepage = @account.homepage if @account
    end

    def homepage_params
      params.require(:homepage).permit(:content, :account_id)
    end

    def set_page_information
      @page_title = 'Homepage'
      @page_icon = 'home'
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@user = User.new
  	@root = true;
  end

  def learn
  end

  def help
  end
end
	

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def active(path)
		('active' if current_page?(path))
	end
end

app/helpers/homepages_helper.rb
module HomepagesHelper

	def homepage_creator
		@account.nickname || @account.first_name || 'ANONYMOUS'
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">

    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
    <br><br>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
    <br><br>
    <%= f.label :nickname %><br>
    <%= f.text_field :nickname, placeholder: 'none' %>
    <br><br>
    <%= f.label :paypal_address %><br>
    <%= f.text_field :paypal_address %>
    <br><br>
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Edit account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table class="pure-table">
  <thead>
  <tr>
    <th>
      User
    </th>
    <th>
      Nickname
    </th>
    <th>
      Link
    </th>
  </tr>
  </thead>
  <% @accounts.each do |account| %>
    <tr>
      <td>
        <%= account.user_id %>
      </td>
      <td>
        <%= account.nickname || 'none' %>
      </td>
      <td>
        <%= link_to 'Homepage', account_homepage_path(account.homepage_id) %>
      </td>
    </tr>
  <% end %>
</table>
<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<% if current_user %>
	<h2>This is your Account</h2>
	<p>First Name: <b><%= @account.first_name || 'none' %></b></p>
	<p>Last Name: <b><%= @account.last_name || 'none' %></b></p>
	<p>Nickname: <b><%= @account.nickname || 'none' %></b></p>
	<p>Paypal Address: <b><%= @account.paypal_address || 'none' %></b></p>
<% else %>
	<%= @account.user.email %>'s account
<% end %>
<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/homepages/_form.html.erb
<%= form_for(@homepage) do |f| %>
  <% if @homepage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@homepage.errors.count, "error") %> prohibited this homepage from being saved:</h2>

      <ul>
      <% @homepage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Content %><br>
    <%= f.text_area :Content %>
  </div>
  <div class="field">
    <%= f.label :User_id %><br>
    <%= f.text_field :User_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homepages/edit.html.erb
<% @header = false %>
<% stylesheet_link_tag('spooner/base.css') %>


<script>
	if ($('document').ready) { $('#navigation-main').fadeOut() }
</script>

<div class="sp-title">
	<div class="text-center" onload="$(this).fadeOut();">
		<%= image_tag 'Spooner.png', class: 'spooner-img' %>
		<h2>Lightweight Website Editor</h2>
	</div>
</div>

<%= render 'spooner/toolbar' %>

<div class="sp-workbench-container">
	<div class="sp-workbench" id="sp-wb-source">
		<h1>Source</h1>
	</div>
	<div class="sp-workbench" id="sp-wb-settings">
		<h1>Settings</h1>
	</div>
</div>

<div class="dock top left fixed" >
	<%= button_to account_homepage_path, method: 'get', class: 'pure-button' do %>
		<%= fa_icon 'arrow-circle-left', class: 'fa-fw' %>
	<% end %>
</div>

<div class="dock top right fixed">



	<%= link_to save_homepage_path(@homepage), method: :put, class: 'pure-button pure-button-catch' do %>
		<%= fa_icon 'save' %>
	<% end %>



	<button class="pure-button">
		<%= fa_icon 'save', class: 'fa-fw' %>
	</button>	
	<%= render 'shared/quickmenu' %>
</div>


<script>
	var zMax = 100;

	function spButton(action) {
		switch(action) {
			case 'source':
				zMax = zMax + 1;
				$('#sp-wb-source').css('zIndex', zMax + 1);
				break;
			case 'settings':
				zMax = zMax + 1;
				$('#sp-wb-settings').css('zIndex', zMax + 1);
				break;
		}
	}
</script>

app/views/homepages/index.html.erb
<h1>Listing homepages</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @homepages.each do |homepage| %>
      <tr>
        <td><%= homepage.account.nickname || homepage.account.first_name || '???' %></td>
        <td><%= link_to 'Show', account_homepage_path(homepage) %></td>
        <td><%= link_to 'Edit', edit_account_homepage_path(homepage) %></td>
        <td><%= link_to 'Reset', account_homepage_path(homepage), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/homepages/new.html.erb
<h1>New homepage</h1>

<%= render 'form' %>

<%= link_to 'Back', homepages_path %>

app/views/homepages/show.html.erb
<% @notification = 'This is your Homepage.' %>

<% if @homepage.account.user == current_user %>
	<div class="pure-notification">
		<%= fa_icon 'info', class: 'fa-fw', text: @notification %>
		<button onclick="$(this).parent('div').remove()">
			<i class="fa fa-close"></i> Close
		</button>
	<script>
		topHeight = $('#navigation-main').height();
		$('.pure-notification').css('top',topHeight);
	</script>
	</div>

<% end %>

<% if @homepage.content %>
<p id="notice"><%= notice %></p>
  <%= @homepage.content.html_safe %>
<% else %>
<h1>Hello, World!</h1><p>This is your homepage. You can use <b>Spooner</b> below to edit it.<br>have fun!</p>
<% end %>

<%= link_to 'Edit with <b>Spooner</b>'.html_safe, edit_account_homepage_path(@homepage) %> |
<%= link_to 'Back', homepages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HomepageProvider</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,100,700,500' rel='stylesheet' type='text/css'>
	<!--[if lte IE 8]>
		<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/grids-responsive-old-ie-min.css">
	<![endif]-->
		<!--[if gt IE 8]><!-->
		<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/grids-responsive-min.css">
	<!--<![endif]-->
	<link href='http://fonts.googleapis.com/css?family=Ubuntu:400,300,500' rel='stylesheet' type='text/css'>
</head>
<body style="margin-bottom: 20px;">

<% if @splash == true %>
	<script>
	document.getElementById('frame').style.background = 'splash.jpg';
	</script>
<% end %>

<% unless @header == false %>
	<%= render 'shared/header' %>
<% end %>

<div id="frame">
	<div class="alert-box">
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>
	</div>

	<%= yield %>

	<% if @footer %>
		<%= render 'shared/footer' %>
	<% end %>
</div>
</body>
</html>

app/views/shared/_footer.html.erb
<div id="homepage-creator">
  <i>PROUDLY MADE BY <%= homepage_creator %></i>
</div>

<div id="footer" class="footer">
	This awesome Website has been created with <%= link_to 'Foundation', root_path %>, the Homepage Creator!
	<br>
	Create your own <%= link_to 'FREE', new_user_registration_path %> Website!
</div>

app/views/shared/_header.html.erb
<%= render 'shared/navigation_sidebar' %>

<div id="navigation-main" class="pure-menu pure-menu-open pure-menu-horizontal">
	<button id="menu-button" class="pull-right" onclick="toggleMenu()">
		<%= fa_icon 'navicon' %>
	</button>
	<% unless @back %>
		<%= link_to 'Site Title', root_path, class: 'pure-menu-heading' %>
	<% else %>
		<%= link_to 'Go back', :back, class: 'pure-menu-heading' %>
	<% end %>

	<%= render 'shared/header_lg' %>

	<% if @page_title %>

		<script>
			$(function() {
				$('#frame').css('marginTop', '10em');
			});
		</script>

		<div id="page-title">
			<%= fa_icon "#{@page_icon}", text: @page_title %>
		</div>
	<% end %>
</div>

app/views/shared/_header_lg.html.erb
<% if signed_in? %>

	<ul>
		<li><%= link_to accounts_path, class: active(accounts_path) do %>
				<%= fa_icon 'users', class: 'fa-fw' %> All Users
			<% end %>
		</li>
		<li>
			<%= link_to homepages_path, class: active(homepages_path) do %>
				<%= fa_icon 'star', class: 'fa-fw' %> Best Sites
			<% end %>
		</li>
		<li><%= link_to show_account_homepage_path(current_user), class: active(show_account_homepage_path(current_user)) do %>
				<%= fa_icon 'home', class: 'fa-fw' %> Homepage
			<% end %>
		</li>
		<li><%= link_to account_path(current_user), class: active(account_path(current_user)) do %>
				<%= fa_icon 'info', class: 'fa-fw' %> Account
			<% end %>
		</li>
		<li><%= link_to root_path do %>
				<%= fa_icon 'dollar', class: 'fa-fw' %> Premium
			<% end %>
		</li>
	</ul>

	<ul class="pull-right">
		<li>
			<%= select_tag 'Language', options_for_select(%w(EN DE FR ES IT)) %>
		</li>
		<li><%= link_to edit_user_registration_path(current_user), class: active(edit_user_registration_path(current_user)) do %>
			<%= fa_icon 'user', class: 'fa-fw' %>
			<%= current_user.email %>
			<% end %>
		</li>
		<li>
			<%= link_to destroy_user_session_path, method: :delete do%>
				<%= fa_icon 'sign-out', class: 'fa-fw' %> Log Out
			<% end %>
		</li>
	</ul>

<% else %>

	<%= render 'shared/welcome_header' %>

<% end %>

app/views/shared/_navigation_sidebar.html.erb
<div id="navigation-sidebar" class="pull-right">

	<h1>Foundation <small>Build on Us</small></h1>
	<p>Select an option</p>
<% if signed_in? %>
	<ul>

		<li>
			<%= link_to(root_path) do %>
				<%= fa_icon 'newspaper-o', class: 'fa-fw'  %> News
			<% end %>
		</li>

		<li><%= link_to accounts_path do %>
				<%= fa_icon 'users', class: 'fa-fw' %> All Users
			<% end %>
		</li>
		
		<li>
			<%= link_to homepages_path do %>
				<%= fa_icon 'star', class: 'fa-fw' %> Best Sites
			<% end %>
		</li>

		<li>
			<%= link_to(root_path) do %>
				<%= fa_icon 'home', class: 'fa-fw'  %> Homepage
			<% end %>
		</li>

		<li>
			<%= link_to(account_path(current_user)) do %>
				<%= fa_icon 'info', class: 'fa-fw' %> Account
			<% end %>
		</li>

		<li>
			<%= link_to(root_path) do %>
				<%= fa_icon 'dollar', class: 'fa-fw'  %> Premium
			<% end %>
		</li>

	</ul>

	<h1>Account Information</h1>
	<p>Logged in as: <b><%= current_user.email %></b></p>

	<ul>
		<li>
			<%= link_to(root_path) do %>
				<%= fa_icon 'cog', class: 'fa-fw'  %> Settings
			<% end %>
		</li>

		<li>
			<%= link_to(edit_user_registration_path(current_user)) do %>
				<%= fa_icon 'user', class: 'fa-fw'  %> Edit Profile
			<% end %>
		</li>

		<li>
			<%= link_to(destroy_user_session_path, method: :delete) do %>
				<%= fa_icon 'sign-out', class: 'fa-fw'  %> Log Out
			<% end %>
		</li>
	</ul>

<% else %>

	<ul>
		<li>
			<%= link_to(new_user_registration_path) do %>
				<%= fa_icon 'asterisk', class: 'fa-fw'  %> Create Account
			<% end %>
		</li>

		<li>
			<%= link_to(new_user_session_path) do %>
				<%= fa_icon 'sign-in', class: 'fa-fw'  %> Sign In
			<% end %>
		</li>

	</ul>

<% end %>

	<ul>
		<li>
			<a onclick='toggleMenu()' style='cursor: pointer'><%= fa_icon 'close', class: 'fa-fw' %> close me</a>
		</li>
	</ul>
</div>

app/views/shared/_quickmenu.html.erb
<button class="pure-button" onclick="toggleMenu()">
	<%= fa_icon 'navicon', class: 'fa-fw' %>
</button>
<%= render 'shared/navigation_sidebar' %>

app/views/shared/_welcome_header.html.erb
<ul class="pull-right">
	<li><%= link_to 'Sign up for an account', new_user_registration_path %></li>
	<li><%= link_to 'Members Area', new_user_session_path %></li>
</ul>

app/views/spooner/_toolbar.html.erb
<div class="sp-toolbar-vertical sp-ui">
	<ul>
		<li><button class="sp-button-tool"><%= fa_icon 'paint-brush', class: 'fa-fw' %></button></li>
		<li><button class="sp-button-tool"><%= fa_icon 'arrows', class: 'fa-fw' %></button></li>
		<li><button onclick="spButton('source');" id="sp-tool-source" class="sp-button-tool"><%= fa_icon 'code', class: 'fa-fw' %></button></li>
		<li><button onclick="spButton('settings');" id="sp-tool-settings" class="sp-button-tool"><%= fa_icon 'cogs', class: 'fa-fw' %></button></li>
		<li><button class="sp-button-tool"><%= fa_icon 'paint-brush', class: 'fa-fw' %></button></li>
		<li><button class="sp-button-tool"><%= fa_icon 'paint-brush', class: 'fa-fw' %></button></li>
		<li><button class="sp-button-tool"><%= fa_icon 'paint-brush', class: 'fa-fw' %></button></li>
		<li><button class="sp-button-tool"><%= fa_icon 'paint-brush', class: 'fa-fw' %></button></li>
		</li>
	</ul>
</div>

app/views/welcome/help.html.erb
<h1>Welcome#help</h1>
<p>Find me in app/views/welcome/help.html.erb</p>

app/views/welcome/index.html.erb
<div class="splash-video hide-on-scroll-large">awd</div>
<div class="splash-background">awd</div>



<div class="scroll-for-more hide-on-scroll">
	<p>Scroll down for more information.</p>
</div>

<div class="welcome-container hide-on-scroll">
	<div class="window-focus text-center">
		<h2>Welcome to</h2>
		<h1>Foundation</h1>
		<h2><b>Foundation</b> lets you design your own, awesome homepage!</h2>
		<form class="pure-form">
			<%= link_to 'sign up', new_user_registration_path, class: 'pure-button pure-button-large pure-button-lead' %>
			<%= link_to 'learn more', learn_more_path, class: 'pure-button pure-button-large pure-button-catch'  %>
		</form>
	</div>
</div>

<div class="content-wrapper">
	<div class="container white">
		<div class="l-box">
			<h1 class="text-center heading">Examples</h1>
			<div class="pure-g">
				<div class="pure-u-1 pure-u-md-1-4">
					<h3><a href="#">Mark</a>'s Website</h3>
					<%= image_tag 'screenshot1.jpg', class: 'pure-img' %>
					<div class="l-box">
						<h3>What do you think about <b>Foundation</b>?</h3>
						<p><i>"I really love my Website. It's so lush and personal. I'm pretty bad at computers, so without <b>Foundation</b>, I never would've been able to do this on my own!"</i></p>
					</div>
				</div>
				<div class="pure-u-1 pure-u-md-1-4">
					<h3><a href="#">Helen</a>'s Website</h3>
					<%= image_tag 'screenshot2.jpg', class: 'pure-img' %>
					<div class="l-box">
						<h3>What do you think about <b>Foundation</b>?</h3>
						<p><i>"As a member of the <b>United Freedom Forces</b>, I am not allowed to own a real Website. That's why I love <b>Foundation</b> so much - it's an enabler!"</i></p>
					</div>
				</div>
				<div class="pure-u-1 pure-u-md-1-4">
					<h3><a href="#">Mark</a>'s Website</h3>
					<%= image_tag 'screenshot1.jpg', class: 'pure-img' %>
					<div class="l-box">
						<h3>What do you think about <b>Foundation</b>?</h3>
						<p><i>"I really love my Website. It's so lush and personal. I'm pretty bad at Computers, so without <b>Foundation</b>, I never would've been able to do this on my own!"</i></p>
					</div>
				</div>
				<div class="pure-u-1 pure-u-md-1-4">
					<h3><a href="#">Helen</a>'s Website</h3>
					<%= image_tag 'screenshot2.jpg', class: 'pure-img' %>
					<div class="l-box">
						<h3>What do you think about <b>Foundation</b>?</h3>
						<p><i>"As a member of the <b>United Freedom Forces</b>, I am not allowed to own a real Website. That's why I love <b>Foundation</b> so much - it's an enabler!"</i></p>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="container white hero">
		<div class="l-box">
			<h1>20$</h1>
			<p class="text-upcase">Lets you join the fun.</p>
			<input type="button" class="pure-button pure-button-primary pure-button-large" value="yes, I want fun!">
			<p>Alternatively, get yourself a <%= link_to 'Free Account', new_user_registration_path %> here.
		</div>
	</div>

	<div class="container white">
		<div class="l-box">
			<h1 class="text-center heading">Homepages Are Fun!</h1>
			<div class="pure-g">
				<div class="pure-u-1 pure-u-md-1-2">
					<div class="l-box">
						<h3>Lorem Ipsum Obey</h3>
						<p>Corrupti ipsam voluptate maxime ducimus fugiat, hic quo facere excepturi asperiores aliquam! Laborum ut veritatis est velit vero ullam consectetur iure laudantium sint, voluptas explicabo similique vitae a ipsum optio!Porro in illo sapiente. Non excepturi perferendis quod dolor vitae doloremque laboriosam omnis consequatur quidem aut, dolore laudantium, cum debitis facere quas, quisquam perspiciatis natus reprehenderit. Delectus eligendi, praesentium rem.</p>
						<p>Minus ad aliquid quibusdam cum nulla, quod harum, tempore illum id quos, cupiditate et beatae quis quasi nemo. Similique debitis architecto at pariatur temporibus nesciunt aut nobis, harum sapiente nulla.</p>
						<p>Accusantium recusandae, qui ex esse vero perferendis nesciunt facere id cum odio hic obcaecati natus itaque minus sunt beatae totam perspiciatis voluptatibus inventore distinctio? Doloribus eum beatae animi ab, omnis!Dolorem temporibus veritatis adipisci corporis, maiores deserunt vel nulla! Laboriosam, at, totam! Labore nostrum ab consequatur illum voluptates atque alias maxime a voluptatum quas dicta, quia voluptate ipsa nesciunt natus? Dolorem temporibus veritatis adipisci corporis, maiores deserunt vel nulla! Laboriosam, at, totam! Labore nostrum ab consequatur illum voluptates atque alias maxime a voluptatum quas dicta, quia voluptate ipsa nesciunt natus?</p>
						<form class="pure-form">
							<button class="pure-button pure-button-primary">sign up</button>
							<button class="pure-button">learn more</button>
						</form>
					</div>
				</div>
				<div class="pure-u-1 pure-u-md-1-2">
					<div class="l-box">
						<h3>Lorem Ipsum Obey</h3>
						<p>Corrupti ipsam voluptate maxime ducimus fugiat, hic quo facere excepturi asperiores aliquam! Laborum ut veritatis est velit vero ullam consectetur iure laudantium sint, voluptas explicabo similique vitae a ipsum optio!Porro in illo sapiente. Non excepturi perferendis quod dolor vitae doloremque laboriosam omnis consequatur quidem aut, dolore laudantium, cum debitis facere quas, quisquam perspiciatis natus reprehenderit. Delectus eligendi, praesentium rem.</p>
						<p>Minus ad aliquid quibusdam cum nulla, quod harum, tempore illum id quos, cupiditate et beatae quis quasi nemo. Similique debitis architecto at pariatur temporibus nesciunt aut nobis, harum sapiente nulla.</p>
						<p>Accusantium recusandae, qui ex esse vero perferendis nesciunt facere id cum odio hic obcaecati natus itaque minus sunt beatae totam perspiciatis voluptatibus inventore distinctio? Doloribus eum beatae animi ab, omnis!Dolorem temporibus veritatis adipisci corporis, maiores deserunt vel nulla! Laboriosam, at, totam! Labore nostrum ab consequatur illum voluptates atque alias maxime a voluptatum quas dicta, quia voluptate ipsa nesciunt natus?Eum rerum deserunt modi, quis non, mollitia temporibus. Eius assumenda, recusandae suscipit, consequuntur voluptates molestiae laudantium fuga nihil ipsa expedita magnam, voluptatibus animi, ipsum. Voluptates nam in aliquam numquam sapiente?</p>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="container darkened text-white fullscreen">
		<div class="l-box center">
			<h1>Register</h1>
			<p>Register your account.</p>
			<form class="pure-form">
			    <fieldset class="pure-group">
			        <input type="text" class="pure-input-1" placeholder="Username">
			        <input type="text" class="pure-input-1" placeholder="Password">
			        <input type="email" class="pure-input-1" placeholder="Email">
			    </fieldset>

			    <fieldset class="pure-group">
			        <input type="text" class="pure-input-1" placeholder="Example Group">
			        <input type="text" class="pure-input-1" placeholder="Purecss Rocks!">
			    </fieldset>

			    <button type="submit" class="pure-button pure-input-1 pure-button-primary">Sign up</button>
			</form>
		</div>
	</div>

</div>